services:
  backend:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    # command: sh -c "chmod -R 755 /var/www/html && chown -R www-data:www-data /var/www/html && apache2-foreground"
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: "10m"

  database:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: "10m"

  adminer:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: "10m"
