name: PHP Base API CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Hosting Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          TARGET: ${{secrets.REMOTE_TARGET}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          EXCLUDE: "/.git/, /.github/, .gitignore, .env.example, .dockerignore, docker-compose.yml, Dockerfile, README.md"
      